unit GoliathTALibrary_Intf;

{----------------------------------------------------------------------------}
{ This unit was automatically generated by the RemObjects SDK after reading  }
{ the RODL file associated with this project .                               }
{                                                                            }
{ Do not modify this unit manually, or your changes will be lost when this   }
{ unit is regenerated the next time you compile the project.                 }
{----------------------------------------------------------------------------}

{$I Remobjects.inc}

interface

uses
  {vcl:} Classes, TypInfo,
  {RemObjects:} uROXMLIntf, uROClasses, uROClient, uROTypes, uROClientIntf,
  {Used RODLs:} DataAbstract4_Intf;

const
  { Library ID }
  LibraryUID = '{6D0793BF-3DF4-4DA5-838E-8F4DC7B69A28}';
  TargetNamespace = '';

  { Service Interface ID's }
  IGoliathTAService_IID : TGUID = '{9D9764E2-F8C0-49AE-ABB9-015CB74CFAC9}';

  { Event ID's }

type
  { Forward declarations }
  IGoliathTAService = interface;





  { Enumerateds }

  { IGoliathTAService }
  IGoliathTAService = interface(IDataAbstractService)
    ['{9D9764E2-F8C0-49AE-ABB9-015CB74CFAC9}']
  end;

  { CoGoliathTAService }
  CoGoliathTAService = class
    class function Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IGoliathTAService;
  end;

  { TGoliathTAService_Proxy }
  TGoliathTAService_Proxy = class(TDataAbstractService_Proxy, IGoliathTAService)
  protected
    function __GetInterfaceName:string; override;

  end;

implementation

uses
  {vcl:} SysUtils,
  {RemObjects:} uROEventRepository, uROSerializer, uRORes;

{ CoGoliathTAService }

class function CoGoliathTAService.Create(const aMessage: IROMessage; aTransportChannel: IROTransportChannel): IGoliathTAService;
begin
  result := TGoliathTAService_Proxy.Create(aMessage, aTransportChannel);
end;

function TGoliathTAService_Proxy.__GetInterfaceName:string;
begin
  result := 'GoliathTAService';
end;

initialization
  RegisterProxyClass(IGoliathTAService_IID, TGoliathTAService_Proxy);


finalization
  UnregisterProxyClass(IGoliathTAService_IID);

end.
